// frontend/src/context/LanguageContext.tsx
import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.quote': 'Get Quote',
    'nav.booking': 'Book Meeting',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.projectWizard': 'Project Wizard',
    
    // Homepage
    'home.hero.title': 'Professional Web Development & AI Integration',
    'home.hero.subtitle': 'Transform your business with cutting-edge web solutions, intelligent automation, and seamless AI integration.',
    'home.hero.cta1': 'Get Started',
    'home.hero.cta2': 'Request Quote',
    'home.hero.cta.ready': 'Ready to Transform Your Business?',
    'home.hero.cta.discuss': "Let's discuss your project and create something amazing together.",
    'home.features.title': 'Why Choose NeuraWeb?',
    'home.features.subtitle': 'We combine technical expertise with business insight to deliver exceptional results.',
    'home.features.fast.title': 'Fast & Efficient',
    'home.features.fast.desc': 'Lightning-fast development with modern tools',
    'home.features.secure.title': 'Secure & Reliable',
    'home.features.secure.desc': 'Enterprise-grade security and reliability',
    'home.features.support.title': '24/7 Support',
    'home.features.support.desc': 'Round-the-clock support for your peace of mind',
    'home.services.subtitle': 'We offer comprehensive solutions to help your business thrive in the digital age.',

    // Login
      "login.signin.title": "Sign in to your account",
      "login.create.title": "Create your account",
      "login.no.account": "Don't have an account? ",
      "login.have.account": "Already have an account? ",
      "login.signup": "Sign up",
      "login.signin": "Sign in",
      "login.client": "Client",
      "login.admin": "Admin",
      "login.fullname": "Full Name",
      "login.fullname.placeholder": "John Doe",
      "login.email": "Email Address",
      "login.email.placeholder.client": "john@example.com",
      "login.email.placeholder.admin": "",
      "login.password": "Password",
      "login.password.placeholder.client": "••••••••",
      "login.password.placeholder.admin": "",
      "login.confirm.password": "Confirm Password",
      "login.confirm.password.placeholder": "••••••••",
      "login.signin.button": "Sign In",
      "login.signup.button": "Sign Up",
      "login.demo.credentials": "",
      "login.demo.email.text": "",
      "login.demo.password.text": "",
      "login.success": "Login successful!",
      "login.register.success": "Registration successful! Please wait for admin validation.",
      "login.passwords.nomatch": "Passwords do not match",
      "login.name.required": "Name is required",
      "login.password.minlength": "Password must be at least 6 characters",
      "login.confirm.password.required": "Please confirm your password",
    
    // Services
    'services.title': 'Our Services',
    'services.web.title': 'Web Development',
    'services.web.desc': 'Custom websites and web applications built with modern technologies.',
    'services.automation.title': 'Automation',
    'services.automation.desc': 'Streamline your processes with intelligent automation solutions.',
    'services.ai.title': 'AI Integration',
    'services.ai.desc': 'Integrate artificial intelligence to enhance your business capabilities.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with us to discuss your project and see how we can help bring your vision to life.',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.success': 'Message sent successfully!',
    'contact.info.title': 'Get in Touch',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.info.location.value': 'Paris, FR, France',
    'contact.why.title': 'Why Work With Us?',
    'contact.why.experience': '• Expert team with 10+ years experience',
    'contact.why.tech': '• Cutting-edge technologies and best practices',
    'contact.why.support': '• Dedicated support throughout the project',
    'contact.why.pricing': '• Transparent pricing and timelines',
    
    // Quote
    'quote.title': 'Request a Quote',
    'quote.subtitle': 'Tell us about your project and get an instant estimate. We\'ll provide a detailed quote within 24 hours.',
    'quote.service': 'Service Type',
    'quote.service.placeholder': 'Select a service...',
    'quote.service.showcase': 'Showcase Website',
    'quote.service.ecommerce': 'E-commerce Platform',
    'quote.service.automation': 'Automation Bot',
    'quote.service.ai': 'AI Integration',
    'quote.options': 'Additional Options',
    'quote.option.design': 'Custom Design',
    'quote.option.maintenance': 'Maintenance Package',
    'quote.option.support': 'Priority Support',
    'quote.estimate': 'Estimated Price',
    'quote.estimate.total': 'Total',
    'quote.estimate.disclaimer': '*This is an estimated price. Final quote may vary based on specific requirements.',
    'quote.estimate.included': 'What\'s Included:',
    'quote.estimate.included.design': '• Professional design & development',
    'quote.estimate.included.responsive': '• Responsive mobile-friendly layout',
    'quote.estimate.included.seo': '• SEO optimization',
    'quote.estimate.included.warranty': '• 3 months warranty',
    'quote.submit': 'Request Quote',
    'quote.success': 'Quote request submitted successfully!',
    'quote.details': 'Additional Details',
    'quote.details.placeholder': 'Tell us more about your project requirements...',
    
    // Booking
    'booking.title': 'Book a Meeting',
    'booking.subtitle': 'Schedule a free consultation to discuss your project requirements and explore how we can help.',
    'booking.select': 'Select a time slot',
    'booking.book': 'Book Meeting',
    'booking.success': 'Meeting booked successfully!',
    'booking.info.title': 'Your Information',
    'booking.phone': 'Phone Number',
    'booking.discuss': 'What would you like to discuss?',
    'booking.discuss.placeholder': 'Tell us about your project or questions you\'d like to discuss...',
    'booking.selected': 'Selected Time Slot:',
    'booking.available': 'Available',
    'booking.booked': 'Booked',
    'booking.meeting.time': 'Meeting Time:',
    'booking.slot.select.error': 'Please select a time slot',

    'booking.select.day': 'Select a Day',
    'booking.select.time': 'Select a Time Slot',
    'booking.back': 'Back',
    'booking.slots.available': 'slots available',
    'booking.slots.full': 'Full',
    'booking.no.days': 'No days available at the moment',
    'booking.select.preferred': 'Select your preferred time slot',
    'booking.time.available': 'Available',
    'booking.time.taken': 'Taken',
    'booking.summary.title': 'Meeting Summary:',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.login': 'Login',
    'admin.email': 'Email',
    'admin.password': 'Password',
    'admin.demo.title': '',
    'admin.demo.email': '',
    'admin.demo.password': '',
    'admin.logout': 'Logout',
    'admin.quotes': 'Quote Requests',
    'admin.contacts': 'Contact Messages',
    'admin.meetings': 'Booked Meetings',
    'admin.status.pending': 'Pending',
    'admin.status.reviewing': 'Reviewing',
    'admin.status.completed': 'Completed',
    'admin.status.confirmed': 'Confirmed',
    'admin.no.quotes': 'No quote requests yet.',
    'admin.no.contacts': 'No contact messages yet.',
    'admin.no.meetings': 'No booked meetings yet.',
    'admin.details': 'Details',
    'admin.service': 'Service:',
    'admin.price': 'Price:',
    'admin.login.success': 'Logged in successfully',
    'admin.login.error': 'Invalid credentials',
    'admin.logout.success': 'Logged out successfully',
    'admin.status.update.success': 'Status updated successfully',
    'admin.status.update.error': 'Error updating status',
    
    // Header
    'header.toggle.theme': 'Toggle theme',
    'header.toggle.language': 'Toggle language',
    'header.toggle.menu': 'Toggle menu',
    'header.logout': 'Logout',

    // Footer
    'footer.company.description': 'Professional web development and AI integration services to transform your business.',
    'footer.services.ecommerce': 'E-commerce Solutions',
    'footer.services.maintenance': 'Maintenance & Support',
    'footer.links.title': 'Quick Links',
    'footer.links.admin': 'Admin Login',
    'footer.copyright': '© 2025 NeuraWeb. All rights reserved.',

    // WizardPage
    'wizard.page.title': 'Project Brief Wizard',
    'wizard.page.subtitle': 'Help us understand your project requirements by completing this comprehensive questionnaire.',
    'wizard.page.submitted.success': 'Project brief submitted successfully!',
    'wizard.page.loading': 'Loading wizard...',
    'wizard.page.validation.pending.title': 'Account Validation Pending',
    'wizard.page.validation.pending.message': 'Your account is currently being reviewed by our admin team. You\'ll be able to access the project wizard once your account is validated.',
    'wizard.page.validation.pending.timeframe': 'This usually takes 24-48 hours. You\'ll receive an email notification once approved.',

     // StepWizard navigation et actions
    'wizard.progress.step': 'Step',
    'wizard.progress.of': 'of',
    'wizard.progress.complete': 'Complete',
    'wizard.navigation.previous': 'Previous',
    'wizard.navigation.next': 'Next',
    'wizard.navigation.save.draft': 'Save Draft',
    'wizard.navigation.submit': 'Submit Project Brief',
    'wizard.navigation.submitted': 'Submitted',
    'wizard.status.saving': 'Saving...',
    'wizard.status.submitting': 'Submitting...',
    'wizard.messages.draft.saved': 'Draft saved',
    'wizard.messages.step.completed': 'Step completed',
    'wizard.messages.save.failed': 'Failed to save step',
    'wizard.messages.submit.success': 'Project brief submitted successfully!',
    'wizard.messages.submit.failed': 'Failed to submit project brief',
    'wizard.messages.fill.required': 'Please fill in the required fields',
    'wizard.messages.no.data': 'No data to save',

    // Project Wizard - Step 1
    'wizard.step1.title': 'General Information',
    'wizard.step1.project.name': 'Project Name',
    'wizard.step1.project.name.placeholder': 'My Awesome Website',
    'wizard.step1.company.name': 'Company/Organization Name',
    'wizard.step1.company.name.placeholder': 'Acme Corporation',
    'wizard.step1.industry': 'Industry/Sector',
    'wizard.step1.industry.placeholder': 'Select an industry',
    'wizard.step1.industry.technology': 'Technology',
    'wizard.step1.industry.healthcare': 'Healthcare',
    'wizard.step1.industry.finance': 'Finance',
    'wizard.step1.industry.education': 'Education',
    'wizard.step1.industry.retail': 'Retail/E-commerce',
    'wizard.step1.industry.manufacturing': 'Manufacturing',
    'wizard.step1.industry.consulting': 'Consulting',
    'wizard.step1.industry.nonprofit': 'Non-profit',
    'wizard.step1.industry.hospitality': 'Hospitality',
    'wizard.step1.industry.realestate': 'Real Estate',
    'wizard.step1.industry.other': 'Other',
    'wizard.step1.project.type': 'Project Type',
    'wizard.step1.project.type.placeholder': 'Select project type',
    'wizard.step1.project.type.new': 'New Website',
    'wizard.step1.project.type.redesign': 'Website Redesign',
    'wizard.step1.project.type.webapp': 'Web Application',
    'wizard.step1.project.type.ecommerce': 'E-commerce Platform',
    'wizard.step1.project.type.mobile': 'Mobile Application',
    'wizard.step1.project.type.automation': 'Process Automation',
    'wizard.step1.project.type.ai': 'AI Integration',
    'wizard.step1.project.type.other': 'Other',
    'wizard.step1.description': 'Project Description',
    'wizard.step1.description.placeholder': 'Provide a brief overview of your project, what you want to achieve, and any specific requirements...',
    'wizard.step1.target.audience': 'Target Audience',
    'wizard.step1.target.audience.placeholder': 'Describe your target audience: demographics, interests, technical proficiency, etc.',
    'wizard.step1.autosaving': 'Auto-saving...',
    'wizard.step1.error.project.name': 'Project name is required',
    'wizard.step1.error.company.name': 'Company name is required',
    'wizard.step1.error.industry': 'Industry is required',
    'wizard.step1.error.project.type': 'Project type is required',
    'wizard.step1.error.description': 'Project description is required',
    'wizard.step1.error.target.audience': 'Target audience is required',

    // Project Wizard - Step 2
    'wizard.step2.title': 'Project Objectives',
    'wizard.step2.primary.goals': 'Primary Goals',
    'wizard.step2.primary.goals.select': 'Select all that apply',
    'wizard.step2.goals.brand': 'Increase brand awareness',
    'wizard.step2.goals.leads': 'Generate leads',
    'wizard.step2.goals.sales': 'Boost online sales',
    'wizard.step2.goals.engagement': 'Improve customer engagement',
    'wizard.step2.goals.processes': 'Streamline business processes',
    'wizard.step2.goals.ux': 'Enhance user experience',
    'wizard.step2.goals.reach': 'Expand market reach',
    'wizard.step2.goals.costs': 'Reduce operational costs',
    'wizard.step2.goals.data': 'Improve data collection',
    'wizard.step2.goals.workflows': 'Automate workflows',
    'wizard.step2.success.metrics': 'Success Metrics',
    'wizard.step2.success.metrics.placeholder': 'How will you measure the success of this project? (e.g., increased traffic, conversion rates, user engagement, etc.)',
    'wizard.step2.challenges': 'Current Challenges',
    'wizard.step2.challenges.placeholder': 'What challenges are you currently facing that this project should address?',
    'wizard.step2.competitors': 'Competitor Analysis',
    'wizard.step2.competitors.placeholder': 'Who are your main competitors? What do you like/dislike about their websites or solutions?',
    'wizard.step2.unique.value': 'Unique Value Proposition',
    'wizard.step2.unique.value.placeholder': 'What makes your business/project unique? What value do you provide that others don\'t?',
    'wizard.step2.error.goals': 'Please select at least one goal',
    'wizard.step2.error.success.metrics': 'Success metrics are required',
    'wizard.step2.error.challenges': 'Current challenges are required',
    'wizard.step2.error.unique.value': 'Unique value proposition is required',

    // Project Wizard - Step 3
    'wizard.step3.title': 'Content & Strategy',
    'wizard.step3.content.strategy': 'Content Strategy',
    'wizard.step3.content.strategy.placeholder': 'Describe your content strategy. What type of content will you publish? How often? What\'s the tone and style?',
    'wizard.step3.existing.content': 'Existing Content',
    'wizard.step3.existing.content.placeholder': 'Do you have existing content (text, images, videos) that needs to be migrated or updated?',
    'wizard.step3.content.creation': 'Content Creation Needs',
    'wizard.step3.content.creation.placeholder': 'Select content creation approach',
    'wizard.step3.content.creation.client': 'We will provide all content',
    'wizard.step3.content.creation.collaborative': 'Collaborative approach (we provide some, you help with some)',
    'wizard.step3.content.creation.fullservice': 'Full-service (you create all content)',
    'wizard.step3.content.creation.mixed': 'Mixed approach (depends on content type)',
    'wizard.step3.languages': 'Languages',
    'wizard.step3.languages.select': 'Select all that apply',
    'wizard.step3.languages.english': 'English',
    'wizard.step3.languages.french': 'French',
    'wizard.step3.languages.spanish': 'Spanish',
    'wizard.step3.languages.german': 'German',
    'wizard.step3.languages.italian': 'Italian',
    'wizard.step3.languages.portuguese': 'Portuguese',
    'wizard.step3.languages.chinese': 'Chinese',
    'wizard.step3.languages.japanese': 'Japanese',
    'wizard.step3.languages.arabic': 'Arabic',
    'wizard.step3.languages.other': 'Other',
    'wizard.step3.seo.requirements': 'SEO Requirements',
    'wizard.step3.seo.requirements.placeholder': 'Do you have specific SEO requirements? Target keywords, local SEO needs, etc.',
    'wizard.step3.content.management': 'Content Management Preferences',
    'wizard.step3.content.management.placeholder': 'Select content management approach',
    'wizard.step3.content.management.easy': 'Easy-to-use CMS (WordPress, etc.)',
    'wizard.step3.content.management.advanced': 'Advanced CMS with more features',
    'wizard.step3.content.management.headless': 'Headless CMS for flexibility',
    'wizard.step3.content.management.static': 'Static content (no frequent updates)',
    'wizard.step3.content.management.custom': 'Custom solution',
    'wizard.step3.content.management.unsure': 'Not sure, need recommendations',
    'wizard.step3.error.content.strategy': 'Content strategy is required',
    'wizard.step3.error.content.creation': 'Content creation preference is required',
    'wizard.step3.error.languages': 'Please select at least one language',
    'wizard.step3.error.content.management': 'Content management preference is required',

    // Project Wizard - Step 4
    'wizard.step4.title': 'Features & Functionality',
    'wizard.step4.core.features': 'Core Features',
    'wizard.step4.core.features.select': 'Select all that apply',
    'wizard.step4.features.contact': 'Contact forms',
    'wizard.step4.features.newsletter': 'Newsletter signup',
    'wizard.step4.features.blog': 'Blog/News section',
    'wizard.step4.features.gallery': 'Photo gallery',
    'wizard.step4.features.video': 'Video integration',
    'wizard.step4.features.social': 'Social media integration',
    'wizard.step4.features.search': 'Search functionality',
    'wizard.step4.features.profiles': 'User profiles',
    'wizard.step4.features.comments': 'Comments system',
    'wizard.step4.features.reviews': 'Rating/Review system',
    'wizard.step4.features.booking': 'Booking/Appointment system',
    'wizard.step4.features.ecommerce': 'E-commerce functionality',
    'wizard.step4.features.inventory': 'Inventory management',
    'wizard.step4.features.analytics': 'Analytics dashboard',
    'wizard.step4.features.multilang': 'Multi-language support',
    'wizard.step4.user.auth': 'User Authentication Requirements',
    'wizard.step4.user.auth.placeholder': 'Select authentication needs',
    'wizard.step4.user.auth.none': 'No user authentication needed',
    'wizard.step4.user.auth.basic': 'Basic login/registration',
    'wizard.step4.user.auth.social': 'Social media login (Google, Facebook, etc.)',
    'wizard.step4.user.auth.advanced': 'Advanced user management with roles',
    'wizard.step4.user.auth.sso': 'Single Sign-On (SSO)',
    'wizard.step4.user.auth.custom': 'Custom authentication solution',
    'wizard.step4.payment': 'Payment Integration',
    'wizard.step4.payment.placeholder': 'Select payment needs',
    'wizard.step4.payment.none': 'No payment processing needed',
    'wizard.step4.payment.stripe': 'Stripe',
    'wizard.step4.payment.paypal': 'PayPal',
    'wizard.step4.payment.square': 'Square',
    'wizard.step4.payment.multiple': 'Multiple payment gateways',
    'wizard.step4.payment.subscription': 'Subscription/recurring payments',
    'wizard.step4.payment.custom': 'Custom payment solution',
    'wizard.step4.integrations': 'Third-party Integrations',
    'wizard.step4.integrations.select': 'Select all that apply',
    'wizard.step4.integrations.analytics': 'Google Analytics',
    'wizard.step4.integrations.maps': 'Google Maps',
    'wizard.step4.integrations.socialmedia': 'Social media platforms',
    'wizard.step4.integrations.email': 'Email marketing tools',
    'wizard.step4.integrations.crm': 'CRM systems',
    'wizard.step4.integrations.payments': 'Payment gateways',
    'wizard.step4.integrations.shipping': 'Shipping providers',
    'wizard.step4.integrations.accounting': 'Accounting software',
    'wizard.step4.integrations.support': 'Customer support tools',
    'wizard.step4.integrations.marketing': 'Marketing automation',
    'wizard.step4.integrations.api': 'API integrations',
    'wizard.step4.integrations.other': 'Other',
    'wizard.step4.custom.functionality': 'Custom Functionality',
    'wizard.step4.custom.functionality.placeholder': 'Describe any custom functionality or unique features you need that weren\'t listed above...',
    'wizard.step4.mobile.requirements': 'Mobile Requirements',
    'wizard.step4.mobile.requirements.placeholder': 'Select mobile approach',
    'wizard.step4.mobile.responsive': 'Responsive web design (works on all devices)',
    'wizard.step4.mobile.first': 'Mobile-first design approach',
    'wizard.step4.mobile.pwa': 'Progressive Web App (PWA)',
    'wizard.step4.mobile.native': 'Native mobile app (iOS/Android)',
    'wizard.step4.mobile.hybrid': 'Hybrid mobile app',
    'wizard.step4.mobile.desktop': 'Desktop only (no mobile optimization)',
    'wizard.step4.error.core.features': 'Please select at least one feature',
    'wizard.step4.error.mobile.requirements': 'Mobile requirements are required',

    // Project Wizard - Step 5
    'wizard.step5.title': 'Design & Branding',
    'wizard.step5.design.style': 'Design Style Preference',
    'wizard.step5.design.style.placeholder': 'Select design style',
    'wizard.step5.design.style.modern': 'Modern & Minimalist',
    'wizard.step5.design.style.corporate': 'Corporate & Professional',
    'wizard.step5.design.style.creative': 'Creative & Artistic',
    'wizard.step5.design.style.bold': 'Bold & Vibrant',
    'wizard.step5.design.style.elegant': 'Elegant & Sophisticated',
    'wizard.step5.design.style.playful': 'Playful & Fun',
    'wizard.step5.design.style.industrial': 'Industrial & Tech',
    'wizard.step5.design.style.vintage': 'Vintage & Retro',
    'wizard.step5.design.style.clean': 'Clean & Simple',
    'wizard.step5.design.style.custom': 'Custom (will describe)',
    'wizard.step5.color.preferences': 'Color Preferences',
    'wizard.step5.color.preferences.placeholder': 'Describe your color preferences. Do you have brand colors? Any colors to avoid? Preferred color schemes?',
    'wizard.step5.brand.guidelines': 'Existing Brand Guidelines',
    'wizard.step5.brand.guidelines.placeholder': 'Do you have existing brand guidelines, style guides, or brand assets we should follow?',
    'wizard.step5.inspiration.sites': 'Inspiration Websites',
    'wizard.step5.inspiration.sites.placeholder': 'Share URLs of websites you like and explain what you like about them (design, functionality, layout, etc.)',
    'wizard.step5.logo.requirements': 'Logo Requirements',
    'wizard.step5.logo.requirements.placeholder': 'Select logo needs',
    'wizard.step5.logo.have': 'We have an existing logo',
    'wizard.step5.logo.need': 'We need a new logo designed',
    'wizard.step5.logo.update': 'We want to update our existing logo',
    'wizard.step5.logo.none': 'No logo needed',
    'wizard.step5.image.requirements': 'Image & Media Requirements',
    'wizard.step5.image.requirements.placeholder': 'Select image approach',
    'wizard.step5.image.client': 'We will provide all images/media',
    'wizard.step5.image.stock': 'Use stock photos/media',
    'wizard.step5.image.professional': 'Need professional photography',
    'wizard.step5.image.mixed': 'Mixed approach (some provided, some sourced)',
    'wizard.step5.image.custom': 'Need custom graphics/illustrations',
    'wizard.step5.image.minimal': 'Minimal image requirements',
    'wizard.step5.error.design.style': 'Design style is required',
    'wizard.step5.error.color.preferences': 'Color preferences are required',
    'wizard.step5.error.image.requirements': 'Image requirements are required',

    // Project Wizard - Step 6 (Hosting)
    'wizard.step6.title': 'Hosting & Infrastructure',
    'wizard.step6.hosting.preference': 'Hosting Preference',
    'wizard.step6.hosting.preference.placeholder': 'Select hosting preference',
    'wizard.step6.hosting.managed': 'Fully managed hosting (we handle everything)',
    'wizard.step6.hosting.shared': 'Shared hosting (cost-effective)',
    'wizard.step6.hosting.vps': 'VPS hosting (more control and resources)',
    'wizard.step6.hosting.dedicated': 'Dedicated server (maximum performance)',
    'wizard.step6.hosting.cloud': 'Cloud hosting (AWS, Google Cloud, etc.)',
    'wizard.step6.hosting.existing': 'Use existing hosting',
    'wizard.step6.hosting.recommendations': 'Need recommendations',
    'wizard.step6.domain.requirements': 'Domain Requirements',
    'wizard.step6.domain.requirements.placeholder': 'Select domain needs',
    'wizard.step6.domain.have': 'We already have a domain',
    'wizard.step6.domain.need': 'We need a new domain',
    'wizard.step6.domain.transfer': 'We need to transfer our domain',
    'wizard.step6.domain.subdomain': 'We\'ll use a subdomain',
    'wizard.step6.domain.multiple': 'We need multiple domains',
    'wizard.step6.domain.help': 'Need help choosing a domain',
    'wizard.step6.performance.requirements': 'Performance Requirements',
    'wizard.step6.performance.requirements.placeholder': 'Select performance needs',
    'wizard.step6.performance.basic': 'Basic performance (small website, low traffic)',
    'wizard.step6.performance.standard': 'Standard performance (medium traffic)',
    'wizard.step6.performance.high': 'High performance (high traffic, fast loading)',
    'wizard.step6.performance.enterprise': 'Enterprise level (maximum performance)',
    'wizard.step6.performance.global': 'Global performance (CDN, multiple regions)',
    'wizard.step6.performance.unsure': 'Not sure, need recommendations',
    'wizard.step6.security.requirements': 'Security Requirements (Select all that apply)',
    'wizard.step6.security.ssl': 'SSL Certificate',
    'wizard.step6.security.updates': 'Regular security updates',
    'wizard.step6.security.malware': 'Malware scanning',
    'wizard.step6.security.firewall': 'Firewall protection',
    'wizard.step6.security.ddos': 'DDoS protection',
    'wizard.step6.security.2fa': 'Two-factor authentication',
    'wizard.step6.security.audits': 'Regular security audits',
    'wizard.step6.security.gdpr': 'GDPR compliance',
    'wizard.step6.security.pci': 'PCI compliance',
    'wizard.step6.security.custom': 'Custom security measures',
    'wizard.step6.backup.requirements': 'Backup Requirements',
    'wizard.step6.backup.requirements.placeholder': 'Select backup needs',
    'wizard.step6.backup.daily': 'Daily automated backups',
    'wizard.step6.backup.weekly': 'Weekly automated backups',
    'wizard.step6.backup.monthly': 'Monthly automated backups',
    'wizard.step6.backup.realtime': 'Real-time backups',
    'wizard.step6.backup.manual': 'Manual backups only',
    'wizard.step6.backup.none': 'No backup requirements',
    'wizard.step6.support.needs': 'Technical Support Needs',
    'wizard.step6.support.needs.placeholder': 'Select support level',
    'wizard.step6.support.basic': 'Basic support (email, business hours)',
    'wizard.step6.support.standard': 'Standard support (email/phone, extended hours)',
    'wizard.step6.support.priority': 'Priority support (24/7, faster response)',
    'wizard.step6.support.managed': 'Fully managed (we handle all technical issues)',
    'wizard.step6.support.self': 'Self-managed (minimal support needed)',
    'wizard.step6.support.custom': 'Custom support arrangement',
    'wizard.step6.error.hosting.preference': 'Hosting preference is required',
    'wizard.step6.error.domain.requirements': 'Domain requirements are required',
    'wizard.step6.error.performance.requirements': 'Performance requirements are required',
    'wizard.step6.error.backup.requirements': 'Backup requirements are required',
    'wizard.step6.error.support.needs': 'Technical support needs are required',

    // Project Wizard - Step 7 (Evolution)
    'wizard.step7.title': 'Future Evolution & Maintenance',
    'wizard.step7.future.features': 'Future Features (Select features you might want to add later)',
    'wizard.step7.features.analytics': 'Advanced analytics and reporting',
    'wizard.step7.features.ai': 'AI-powered features',
    'wizard.step7.features.mobile': 'Mobile app development',
    'wizard.step7.features.ecommerce': 'Advanced e-commerce features',
    'wizard.step7.features.multilang': 'Multi-language expansion',
    'wizard.step7.features.api': 'API integrations',
    'wizard.step7.features.users': 'Advanced user management',
    'wizard.step7.features.automation': 'Automation workflows',
    'wizard.step7.features.seo': 'Advanced SEO features',
    'wizard.step7.features.social': 'Social media integration',
    'wizard.step7.features.security': 'Advanced security features',
    'wizard.step7.features.performance': 'Performance optimization',
    'wizard.step7.features.integrations': 'Custom integrations',
    'wizard.step7.features.cms': 'Advanced content management',
    'wizard.step7.features.marketing': 'Marketing automation',
    'wizard.step7.scalability.needs': 'Scalability Requirements',
    'wizard.step7.scalability.needs.placeholder': 'Select scalability needs',
    'wizard.step7.scalability.minimal': 'Minimal growth expected',
    'wizard.step7.scalability.moderate': 'Moderate growth expected',
    'wizard.step7.scalability.high': 'High growth expected',
    'wizard.step7.scalability.enterprise': 'Enterprise-level scalability needed',
    'wizard.step7.scalability.global': 'Global expansion planned',
    'wizard.step7.scalability.unsure': 'Unsure about future growth',
    'wizard.step7.maintenance.preference': 'Maintenance Preference',
    'wizard.step7.maintenance.preference.placeholder': 'Select maintenance approach',
    'wizard.step7.maintenance.full': 'Full-service maintenance (we handle everything)',
    'wizard.step7.maintenance.partial': 'Partial maintenance (we handle technical, you handle content)',
    'wizard.step7.maintenance.training': 'Training-based (we train your team)',
    'wizard.step7.maintenance.self': 'Self-managed (minimal ongoing support)',
    'wizard.step7.maintenance.asneeded': 'As-needed support (pay per request)',
    'wizard.step7.maintenance.custom': 'Custom maintenance plan',
    'wizard.step7.update.frequency': 'Expected Update Frequency',
    'wizard.step7.update.frequency.placeholder': 'Select update frequency',
    'wizard.step7.update.daily': 'Daily updates',
    'wizard.step7.update.weekly': 'Weekly updates',
    'wizard.step7.update.monthly': 'Monthly updates',
    'wizard.step7.update.quarterly': 'Quarterly updates',
    'wizard.step7.update.rarely': 'Rarely (static content)',
    'wizard.step7.update.seasonal': 'Seasonal updates',
    'wizard.step7.update.asneeded': 'As needed',
    'wizard.step7.training.needs': 'Training Requirements',
    'wizard.step7.training.needs.placeholder': 'Select training needs',
    'wizard.step7.training.none': 'No training needed',
    'wizard.step7.training.basic': 'Basic training (content updates)',
    'wizard.step7.training.comprehensive': 'Comprehensive training (all features)',
    'wizard.step7.training.ongoing': 'Ongoing training and support',
    'wizard.step7.training.documentation': 'Documentation only',
    'wizard.step7.training.video': 'Video tutorials',
    'wizard.step7.training.live': 'Live training sessions',
    'wizard.step7.longterm.vision': 'Long-term Vision',
    'wizard.step7.longterm.vision.placeholder': 'Describe your long-term vision for this project. Where do you see it in 2-3 years? What are your growth plans?',
    'wizard.step7.error.scalability.needs': 'Scalability needs are required',
    'wizard.step7.error.maintenance.preference': 'Maintenance preference is required',
    'wizard.step7.error.update.frequency': 'Update frequency is required',

    // Project Wizard - Step 8 (Budget)
    'wizard.step8.title': 'Budget & Timeline',
    'wizard.step8.budget.range': 'Budget Range',
    'wizard.step8.budget.range.placeholder': 'Select budget range',
    'wizard.step8.budget.under5k': 'Under $5,000',
    'wizard.step8.budget.5k10k': '$5,000 - $10,000',
    'wizard.step8.budget.10k25k': '$10,000 - $25,000',
    'wizard.step8.budget.25k50k': '$25,000 - $50,000',
    'wizard.step8.budget.50k100k': '$50,000 - $100,000',
    'wizard.step8.budget.over100k': 'Over $100,000',
    'wizard.step8.budget.discuss': 'Prefer to discuss',
    'wizard.step8.budget.flexibility': 'Budget Flexibility',
    'wizard.step8.budget.flexibility.placeholder': 'Select flexibility level',
    'wizard.step8.flexibility.fixed': 'Fixed budget (cannot exceed)',
    'wizard.step8.flexibility.some': 'Some flexibility (up to 10-20% more)',
    'wizard.step8.flexibility.flexible': 'Flexible (willing to invest more for quality)',
    'wizard.step8.flexibility.value': 'Value-focused (best ROI within reason)',
    'wizard.step8.flexibility.phased': 'Open to phased approach',
    'wizard.step8.payment.preference': 'Payment Preference',
    'wizard.step8.payment.preference.placeholder': 'Select payment structure',
    'wizard.step8.payment.milestone': 'Milestone-based payments',
    'wizard.step8.payment.monthly': 'Monthly payments',
    'wizard.step8.payment.5050': '50% upfront, 50% on completion',
    'wizard.step8.payment.thirds': 'Three equal payments',
    'wizard.step8.payment.completion': 'Full payment on completion',
    'wizard.step8.payment.custom': 'Custom payment plan',
    'wizard.step8.timeline': 'Desired Timeline',
    'wizard.step8.timeline.placeholder': 'Select timeline',
    'wizard.step8.timeline.asap': 'ASAP (rush project)',
    'wizard.step8.timeline.1month': 'Within 1 month',
    'wizard.step8.timeline.2to3months': '2-3 months',
    'wizard.step8.timeline.3to6months': '3-6 months',
    'wizard.step8.timeline.6to12months': '6-12 months',
    'wizard.step8.timeline.overyear': 'Over 1 year',
    'wizard.step8.timeline.flexible': 'Flexible timeline',
    'wizard.step8.priority.features': 'Priority Features (if budget is limited)',
    'wizard.step8.priority.features.placeholder': 'If we need to work within a tighter budget, which features are most important to you? What can be added later?',
    'wizard.step8.budget.concerns': 'Budget Concerns or Questions',
    'wizard.step8.budget.concerns.placeholder': 'Do you have any concerns about the budget? Questions about pricing? Anything else we should know?',
    'wizard.step8.error.budget.range': 'Budget range is required',
    'wizard.step8.error.budget.flexibility': 'Budget flexibility is required',
    'wizard.step8.error.payment.preference': 'Payment preference is required',
    'wizard.step8.error.timeline': 'Timeline is required',
    'wizard.step8.error.priority.features': 'Priority features are required',

    // Project Wizard - Step 9 (Other)
    'wizard.step9.title': 'Final Details',
    'wizard.step9.additional.requirements': 'Additional Requirements',
    'wizard.step9.additional.requirements.placeholder': 'Any additional requirements, features, or specifications that weren\'t covered in the previous steps?',
    'wizard.step9.concerns': 'Concerns or Challenges',
    'wizard.step9.concerns.placeholder': 'Do you have any concerns about the project? Past experiences with web development? Specific challenges you\'re worried about?',
    'wizard.step9.questions': 'Questions for Us',
    'wizard.step9.questions.placeholder': 'What questions do you have for us? About our process, timeline, pricing, or anything else?',
    'wizard.step9.communication.preference': 'Communication Preference',
    'wizard.step9.communication.preference.placeholder': 'Select communication preference',
    'wizard.step9.communication.email': 'Email',
    'wizard.step9.communication.phone': 'Phone calls',
    'wizard.step9.communication.video': 'Video calls',
    'wizard.step9.communication.slack': 'Slack/Teams',
    'wizard.step9.communication.project': 'Project management tool',
    'wizard.step9.communication.mixed': 'Mixed approach',
    'wizard.step9.decision.makers': 'Decision Makers',
    'wizard.step9.decision.makers.placeholder': 'Who will be involved in making decisions about this project? Should we include anyone else in communications?',
    'wizard.step9.additional.info': 'Anything Else?',
    'wizard.step9.additional.info.placeholder': 'Is there anything else you\'d like us to know about your project, your business, or your expectations?',
    'wizard.step9.ready.title': 'Ready to Submit Your Project Brief?',
    'wizard.step9.ready.description': 'Once you submit this project brief, our team will review your requirements and get back to you within 24-48 hours with:',
    'wizard.step9.ready.proposal': 'A detailed project proposal',
    'wizard.step9.ready.pricing': 'Accurate timeline and pricing',
    'wizard.step9.ready.nextsteps': 'Next steps for moving forward',
    'wizard.step9.ready.answers': 'Answers to any questions you\'ve asked',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.name.required': 'Name is required',
    'common.email.required': 'Email is required',
    'common.email.invalid': 'Please enter a valid email address',
    'common.message.required': 'Message is required',
    'common.password.required': 'Password is required',
    'common.service.required': 'Please select a service type',
    'common.required': 'Required',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.quote': 'Devis',
    'nav.booking': 'Rendez-vous',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    'nav.projectWizard': 'Assistant Projet',
    
    // Homepage
    'home.hero.title': 'Développement Web Professionnel & Intégration IA',
    'home.hero.subtitle': 'Transformez votre entreprise avec des solutions web de pointe, une automatisation intelligente et une intégration IA transparente.',
    'home.hero.cta1': 'Commencer',
    'home.hero.cta2': 'Demander un Devis',
    'home.hero.cta.ready': 'Prêt à Transformer Votre Entreprise ?',
    'home.hero.cta.discuss': 'Discutons de votre projet et créons quelque chose d\'extraordinaire ensemble.',
    'home.features.title': 'Pourquoi Choisir NeuraWeb ?',
    'home.features.subtitle': 'Nous combinons l\'expertise technique avec l\'intelligence business pour livrer des résultats exceptionnels.',
    'home.features.fast.title': 'Rapide & Efficace',
    'home.features.fast.desc': 'Développement ultra-rapide avec des outils modernes',
    'home.features.secure.title': 'Sécurisé & Fiable',
    'home.features.secure.desc': 'Sécurité et fiabilité de niveau entreprise',
    'home.features.support.title': 'Support 24/7',
    'home.features.support.desc': 'Support continu pour votre tranquillité d\'esprit',
    'home.services.subtitle': 'Nous offrons des solutions complètes pour aider votre entreprise à prospérer à l\'ère numérique.',

    // Contact
    "login.signin.title": "Connectez-vous à votre compte",
    "login.create.title": "Créez votre compte",
    "login.no.account": "Vous n'avez pas de compte ? ",
    "login.have.account": "Vous avez déjà un compte ? ",
    "login.signup": "S'inscrire",
    "login.signin": "Se connecter",
    "login.client": "Client",
    "login.admin": "Admin",
    "login.fullname": "Nom Complet",
    "login.fullname.placeholder": "Jean Dupont",
    "login.email": "Adresse Email",
    "login.email.placeholder.client": "jean@exemple.com",
    "login.email.placeholder.admin": "",
    "login.password": "Mot de Passe",
    "login.password.placeholder.client": "••••••••",
    "login.password.placeholder.admin": "",
    "login.confirm.password": "Confirmer le Mot de Passe",
    "login.confirm.password.placeholder": "••••••••",
    "login.signin.button": "Se Connecter",
    "login.signup.button": "S'Inscrire",
    "login.demo.credentials": "",
    "login.demo.email.text": "",
    "login.demo.password.text": "",
    "login.success": "Connexion réussie !",
    "login.register.success": "Inscription réussie ! Veuillez attendre la validation de l'administrateur.",
    "login.passwords.nomatch": "Les mots de passe ne correspondent pas",
    "login.name.required": "Le nom est requis",
    "login.password.minlength": "Le mot de passe doit contenir au moins 6 caractères",
    "login.confirm.password.required": "Veuillez confirmer votre mot de passe",
    
    // Services
    'services.title': 'Nos Services',
    'services.web.title': 'Développement Web',
    'services.web.desc': 'Sites web et applications web personnalisés construits avec des technologies modernes.',
    'services.automation.title': 'Automatisation',
    'services.automation.desc': 'Optimisez vos processus avec des solutions d\'automatisation intelligentes.',
    'services.ai.title': 'Intégration IA',
    'services.ai.desc': 'Intégrez l\'intelligence artificielle pour améliorer les capacités de votre entreprise.',
    
    // Contact
    'contact.title': 'Nous Contacter',
    'contact.subtitle': 'Contactez-nous pour discuter de votre projet et voir comment nous pouvons vous aider à concrétiser votre vision.',
    'contact.name': 'Nom Complet',
    'contact.email': 'Adresse Email',
    'contact.message': 'Votre Message',
    'contact.send': 'Envoyer le Message',
    'contact.success': 'Message envoyé avec succès !',
    'contact.info.title': 'Entrer en Contact',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Téléphone',
    'contact.info.location': 'Localisation',
    'contact.info.location.value': 'Paris, FR, France',
    'contact.why.title': 'Pourquoi Travailler Avec Nous ?',
    'contact.why.experience': '• Équipe d\'experts avec plus de 10 ans d\'expérience',
    'contact.why.tech': '• Technologies de pointe et meilleures pratiques',
    'contact.why.support': '• Support dédié tout au long du projet',
    'contact.why.pricing': '• Tarification et délais transparents',
    
    // Quote
    'quote.title': 'Demander un Devis',
    'quote.subtitle': 'Parlez-nous de votre projet et obtenez une estimation instantanée. Nous fournirons un devis détaillé sous 24 heures.',
    'quote.service': 'Type de Service',
    'quote.service.placeholder': 'Sélectionnez un service...',
    'quote.service.showcase': 'Site Vitrine',
    'quote.service.ecommerce': 'Plateforme E-commerce',
    'quote.service.automation': 'Bot d\'Automatisation',
    'quote.service.ai': 'Intégration IA',
    'quote.options': 'Options Additionnelles',
    'quote.option.design': 'Design Personnalisé',
    'quote.option.maintenance': 'Package Maintenance',
    'quote.option.support': 'Support Prioritaire',
    'quote.estimate': 'Prix Estimé',
    'quote.estimate.total': 'Total',
    'quote.estimate.disclaimer': '*Ceci est un prix estimé. Le devis final peut varier selon les exigences spécifiques.',
    'quote.estimate.included': 'Ce qui est Inclus :',
    'quote.estimate.included.design': '• Design et développement professionnel',
    'quote.estimate.included.responsive': '• Interface responsive adaptée mobile',
    'quote.estimate.included.seo': '• Optimisation SEO',
    'quote.estimate.included.warranty': '• 3 mois de garantie',
    'quote.submit': 'Demander un Devis',
    'quote.success': 'Demande de devis soumise avec succès !',
    'quote.details': 'Détails Supplémentaires',
    'quote.details.placeholder': 'Parlez-nous davantage des exigences de votre projet...',
    
    // Booking
    'booking.title': 'Réserver un Rendez-vous',
    'booking.subtitle': 'Planifiez une consultation gratuite pour discuter des exigences de votre projet et explorer comment nous pouvons vous aider.',
    'booking.select': 'Sélectionnez un créneau',
    'booking.book': 'Réserver',
    'booking.success': 'Rendez-vous réservé avec succès !',
    'booking.info.title': 'Vos Informations',
    'booking.phone': 'Numéro de Téléphone',
    'booking.discuss': 'De quoi aimeriez-vous discuter ?',
    'booking.discuss.placeholder': 'Parlez-nous de votre projet ou des questions que vous aimeriez discuter...',
    'booking.selected': 'Créneau Sélectionné :',
    'booking.available': 'Disponible',
    'booking.booked': 'Réservé',
    'booking.meeting.time': 'Heure du Rendez-vous :',
    'booking.slot.select.error': 'Veuillez sélectionner un créneau horaire',

    'booking.select.day': 'Choisir un Jour',
    'booking.select.time': 'Choisir un Créneau',
    'booking.back': 'Retour',
    'booking.slots.available': 'créneaux disponibles',
    'booking.slots.full': 'Complet',
    'booking.no.days': 'Aucun jour disponible pour le moment',
    'booking.select.preferred': 'Sélectionnez votre créneau préféré',
    'booking.time.available': 'Libre',
    'booking.time.taken': 'Pris',
    'booking.summary.title': 'Résumé du rendez-vous :',
    
    // Admin
    'admin.title': 'Tableau de Bord Admin',
    'admin.login': 'Connexion',
    'admin.email': 'Email',
    'admin.password': 'Mot de Passe',
    'admin.demo.title': '',
    'admin.demo.email': '',
    'admin.demo.password': '',
    'admin.logout': 'Déconnexion',
    'admin.quotes': 'Demandes de Devis',
    'admin.contacts': 'Messages de Contact',
    'admin.meetings': 'Rendez-vous Réservés',
    'admin.status.pending': 'En Attente',
    'admin.status.reviewing': 'En Révision',
    'admin.status.completed': 'Terminé',
    'admin.status.confirmed': 'Confirmé',
    'admin.no.quotes': 'Aucune demande de devis pour le moment.',
    'admin.no.contacts': 'Aucun message de contact pour le moment.',
    'admin.no.meetings': 'Aucun rendez-vous réservé pour le moment.',
    'admin.details': 'Détails',
    'admin.service': 'Service :',
    'admin.price': 'Prix :',
    'admin.login.success': 'Connecté avec succès',
    'admin.login.error': 'Identifiants invalides',
    'admin.logout.success': 'Déconnecté avec succès',
    'admin.status.update.success': 'Statut mis à jour avec succès',
    'admin.status.update.error': 'Erreur lors de la mise à jour du statut',
    
    // Header
    'header.toggle.theme': 'Basculer le thème',
    'header.toggle.language': 'Changer la langue',
    'header.toggle.menu': 'Basculer le menu',
    'header.logout': 'Se déconnecter',

    // Footer
    'footer.company.description': 'Services professionnels de développement web et d\'intégration IA pour transformer votre entreprise.',
    'footer.services.ecommerce': 'Solutions E-commerce',
    'footer.services.maintenance': 'Maintenance et Support',
    'footer.links.title': 'Liens Rapides',
    'footer.links.admin': 'Connexion Admin',
    'footer.copyright': '© 2025 NeuraWeb. Tous droits réservés.',

    // WizardPage
    'wizard.page.title': 'Assistant de Brief de Projet',
    'wizard.page.subtitle': 'Aidez-nous à comprendre les exigences de votre projet en complétant ce questionnaire complet.',
    'wizard.page.submitted.success': 'Brief de projet soumis avec succès !',
    'wizard.page.loading': 'Chargement de l\'assistant...',
    'wizard.page.validation.pending.title': 'Validation de Compte en Attente',
    'wizard.page.validation.pending.message': 'Votre compte est actuellement en cours d\'examen par notre équipe d\'administration. Vous pourrez accéder à l\'assistant de projet une fois votre compte validé.',
    'wizard.page.validation.pending.timeframe': 'Cela prend généralement 24 à 48 heures. Vous recevrez une notification par email une fois approuvé.',

    // StepWizard navigation et actions
    'wizard.progress.step': 'Étape',
    'wizard.progress.of': 'sur',
    'wizard.progress.complete': 'Terminé',
    'wizard.navigation.previous': 'Précédent',
    'wizard.navigation.next': 'Suivant',
    'wizard.navigation.save.draft': 'Sauvegarder Brouillon',
    'wizard.navigation.submit': 'Soumettre Brief Projet',
    'wizard.navigation.submitted': 'Soumis',
    'wizard.status.saving': 'Sauvegarde...',
    'wizard.status.submitting': 'Soumission...',
    'wizard.messages.draft.saved': 'Brouillon sauvegardé',
    'wizard.messages.step.completed': 'Étape terminée',
    'wizard.messages.save.failed': 'Échec de la sauvegarde',
    'wizard.messages.submit.success': 'Brief de projet soumis avec succès !',
    'wizard.messages.submit.failed': 'Échec de la soumission du brief',
    'wizard.messages.fill.required': 'Veuillez remplir les champs requis',
    'wizard.messages.no.data': 'Aucune donnée à sauvegarder',

    // Project Wizard - Step 1
    'wizard.step1.title': 'Informations Générales',
    'wizard.step1.project.name': 'Nom du Projet',
    'wizard.step1.project.name.placeholder': 'Mon Site Web Génial',
    'wizard.step1.company.name': 'Nom de l\'Entreprise/Organisation',
    'wizard.step1.company.name.placeholder': 'Acme Corporation',
    'wizard.step1.industry': 'Industrie/Secteur',
    'wizard.step1.industry.placeholder': 'Sélectionnez une industrie',
    'wizard.step1.industry.technology': 'Technologie',
    'wizard.step1.industry.healthcare': 'Santé',
    'wizard.step1.industry.finance': 'Finance',
    'wizard.step1.industry.education': 'Éducation',
    'wizard.step1.industry.retail': 'Commerce/E-commerce',
    'wizard.step1.industry.manufacturing': 'Fabrication',
    'wizard.step1.industry.consulting': 'Conseil',
    'wizard.step1.industry.nonprofit': 'Organisation à but non lucratif',
    'wizard.step1.industry.hospitality': 'Hôtellerie',
    'wizard.step1.industry.realestate': 'Immobilier',
    'wizard.step1.industry.other': 'Autre',
    'wizard.step1.project.type': 'Type de Projet',
    'wizard.step1.project.type.placeholder': 'Sélectionnez le type de projet',
    'wizard.step1.project.type.new': 'Nouveau Site Web',
    'wizard.step1.project.type.redesign': 'Refonte de Site Web',
    'wizard.step1.project.type.webapp': 'Application Web',
    'wizard.step1.project.type.ecommerce': 'Plateforme E-commerce',
    'wizard.step1.project.type.mobile': 'Application Mobile',
    'wizard.step1.project.type.automation': 'Automatisation de Processus',
    'wizard.step1.project.type.ai': 'Intégration IA',
    'wizard.step1.project.type.other': 'Autre',
    'wizard.step1.description': 'Description du Projet',
    'wizard.step1.description.placeholder': 'Fournissez un aperçu de votre projet, ce que vous voulez accomplir, et toute exigence spécifique...',
    'wizard.step1.target.audience': 'Public Cible',
    'wizard.step1.target.audience.placeholder': 'Décrivez votre public cible : démographie, intérêts, compétences techniques, etc.',
    'wizard.step1.autosaving': 'Sauvegarde automatique...',
    'wizard.step1.error.project.name': 'Le nom du projet est requis',
    'wizard.step1.error.company.name': 'Le nom de l\'entreprise est requis',
    'wizard.step1.error.industry': 'L\'industrie est requise',
    'wizard.step1.error.project.type': 'Le type de projet est requis',
    'wizard.step1.error.description': 'La description du projet est requise',
    'wizard.step1.error.target.audience': 'Le public cible est requis',

    // Project Wizard - Step 2
    'wizard.step2.title': 'Objectifs du Projet',
    'wizard.step2.primary.goals': 'Objectifs Principaux',
    'wizard.step2.primary.goals.select': 'Sélectionnez tout ce qui s\'applique',
    'wizard.step2.goals.brand': 'Augmenter la notoriété de la marque',
    'wizard.step2.goals.leads': 'Générer des prospects',
    'wizard.step2.goals.sales': 'Stimuler les ventes en ligne',
    'wizard.step2.goals.engagement': 'Améliorer l\'engagement client',
    'wizard.step2.goals.processes': 'Rationaliser les processus métier',
    'wizard.step2.goals.ux': 'Améliorer l\'expérience utilisateur',
    'wizard.step2.goals.reach': 'Élargir la portée du marché',
    'wizard.step2.goals.costs': 'Réduire les coûts opérationnels',
    'wizard.step2.goals.data': 'Améliorer la collecte de données',
    'wizard.step2.goals.workflows': 'Automatiser les flux de travail',
    'wizard.step2.success.metrics': 'Métriques de Succès',
    'wizard.step2.success.metrics.placeholder': 'Comment mesurerez-vous le succès de ce projet ? (ex: augmentation du trafic, taux de conversion, engagement utilisateur, etc.)',
    'wizard.step2.challenges': 'Défis Actuels',
    'wizard.step2.challenges.placeholder': 'Quels défis rencontrez-vous actuellement que ce projet devrait résoudre ?',
    'wizard.step2.competitors': 'Analyse Concurrentielle',
    'wizard.step2.competitors.placeholder': 'Qui sont vos principaux concurrents ? Qu\'aimez-vous/n\'aimez-vous pas dans leurs sites web ou solutions ?',
    'wizard.step2.unique.value': 'Proposition de Valeur Unique',
    'wizard.step2.unique.value.placeholder': 'Qu\'est-ce qui rend votre entreprise/projet unique ? Quelle valeur offrez-vous que les autres n\'offrent pas ?',
    'wizard.step2.error.goals': 'Veuillez sélectionner au moins un objectif',
    'wizard.step2.error.success.metrics': 'Les métriques de succès sont requises',
    'wizard.step2.error.challenges': 'Les défis actuels sont requis',
    'wizard.step2.error.unique.value': 'La proposition de valeur unique est requise',

    // Project Wizard - Step 3
    'wizard.step3.title': 'Contenu & Stratégie',
    'wizard.step3.content.strategy': 'Stratégie de Contenu',
    'wizard.step3.content.strategy.placeholder': 'Décrivez votre stratégie de contenu. Quel type de contenu publierez-vous ? À quelle fréquence ? Quel est le ton et le style ?',
    'wizard.step3.existing.content': 'Contenu Existant',
    'wizard.step3.existing.content.placeholder': 'Avez-vous du contenu existant (texte, images, vidéos) qui doit être migré ou mis à jour ?',
    'wizard.step3.content.creation': 'Besoins de Création de Contenu',
    'wizard.step3.content.creation.placeholder': 'Sélectionnez l\'approche de création de contenu',
    'wizard.step3.content.creation.client': 'Nous fournirons tout le contenu',
    'wizard.step3.content.creation.collaborative': 'Approche collaborative (nous en fournissons une partie, vous aidez pour le reste)',
    'wizard.step3.content.creation.fullservice': 'Service complet (vous créez tout le contenu)',
    'wizard.step3.content.creation.mixed': 'Approche mixte (dépend du type de contenu)',
    'wizard.step3.languages': 'Langues',
    'wizard.step3.languages.select': 'Sélectionnez tout ce qui s\'applique',
    'wizard.step3.languages.english': 'Anglais',
    'wizard.step3.languages.french': 'Français',
    'wizard.step3.languages.spanish': 'Espagnol',
    'wizard.step3.languages.german': 'Allemand',
    'wizard.step3.languages.italian': 'Italien',
    'wizard.step3.languages.portuguese': 'Portugais',
    'wizard.step3.languages.chinese': 'Chinois',
    'wizard.step3.languages.japanese': 'Japonais',
    'wizard.step3.languages.arabic': 'Arabe',
    'wizard.step3.languages.other': 'Autre',
    'wizard.step3.seo.requirements': 'Exigences SEO',
    'wizard.step3.seo.requirements.placeholder': 'Avez-vous des exigences SEO spécifiques ? Mots-clés cibles, besoins SEO locaux, etc.',
    'wizard.step3.content.management': 'Préférences de Gestion de Contenu',
    'wizard.step3.content.management.placeholder': 'Sélectionnez l\'approche de gestion de contenu',
    'wizard.step3.content.management.easy': 'CMS facile à utiliser (WordPress, etc.)',
    'wizard.step3.content.management.advanced': 'CMS avancé avec plus de fonctionnalités',
    'wizard.step3.content.management.headless': 'CMS découplé pour la flexibilité',
    'wizard.step3.content.management.static': 'Contenu statique (pas de mises à jour fréquentes)',
    'wizard.step3.content.management.custom': 'Solution personnalisée',
    'wizard.step3.content.management.unsure': 'Pas sûr, besoin de recommandations',
    'wizard.step3.error.content.strategy': 'La stratégie de contenu est requise',
    'wizard.step3.error.content.creation': 'La préférence de création de contenu est requise',
    'wizard.step3.error.languages': 'Veuillez sélectionner au moins une langue',
    'wizard.step3.error.content.management': 'La préférence de gestion de contenu est requise',

    // Project Wizard - Step 4
    'wizard.step4.title': 'Fonctionnalités',
    'wizard.step4.core.features': 'Fonctionnalités Principales',
    'wizard.step4.core.features.select': 'Sélectionnez tout ce qui s\'applique',
    'wizard.step4.features.contact': 'Formulaires de contact',
    'wizard.step4.features.newsletter': 'Inscription newsletter',
    'wizard.step4.features.blog': 'Section blog/actualités',
    'wizard.step4.features.gallery': 'Galerie photos',
    'wizard.step4.features.video': 'Intégration vidéo',
    'wizard.step4.features.social': 'Intégration réseaux sociaux',
    'wizard.step4.features.search': 'Fonctionnalité de recherche',
    'wizard.step4.features.profiles': 'Profils utilisateurs',
    'wizard.step4.features.comments': 'Système de commentaires',
    'wizard.step4.features.reviews': 'Système de notation/avis',
    'wizard.step4.features.booking': 'Système de réservation/rendez-vous',
    'wizard.step4.features.ecommerce': 'Fonctionnalité e-commerce',
    'wizard.step4.features.inventory': 'Gestion d\'inventaire',
    'wizard.step4.features.analytics': 'Tableau de bord analytique',
    'wizard.step4.features.multilang': 'Support multi-langues',
    'wizard.step4.user.auth': 'Exigences d\'Authentification Utilisateur',
    'wizard.step4.user.auth.placeholder': 'Sélectionnez les besoins d\'authentification',
    'wizard.step4.user.auth.none': 'Pas d\'authentification utilisateur nécessaire',
    'wizard.step4.user.auth.basic': 'Connexion/inscription de base',
    'wizard.step4.user.auth.social': 'Connexion via réseaux sociaux (Google, Facebook, etc.)',
    'wizard.step4.user.auth.advanced': 'Gestion avancée des utilisateurs avec rôles',
    'wizard.step4.user.auth.sso': 'Authentification unique (SSO)',
    'wizard.step4.user.auth.custom': 'Solution d\'authentification personnalisée',
    'wizard.step4.payment': 'Intégration de Paiement',
    'wizard.step4.payment.placeholder': 'Sélectionnez les besoins de paiement',
    'wizard.step4.payment.none': 'Pas de traitement de paiement nécessaire',
    'wizard.step4.payment.stripe': 'Stripe',
    'wizard.step4.payment.paypal': 'PayPal',
    'wizard.step4.payment.square': 'Square',
    'wizard.step4.payment.multiple': 'Passerelles de paiement multiples',
    'wizard.step4.payment.subscription': 'Paiements par abonnement/récurrents',
    'wizard.step4.payment.custom': 'Solution de paiement personnalisée',
    'wizard.step4.integrations': 'Intégrations Tierces',
    'wizard.step4.integrations.select': 'Sélectionnez tout ce qui s\'applique',
    'wizard.step4.integrations.analytics': 'Google Analytics',
    'wizard.step4.integrations.maps': 'Google Maps',
    'wizard.step4.integrations.socialmedia': 'Plateformes de réseaux sociaux',
    'wizard.step4.integrations.email': 'Outils de marketing par email',
    'wizard.step4.integrations.crm': 'Systèmes CRM',
    'wizard.step4.integrations.payments': 'Passerelles de paiement',
    'wizard.step4.integrations.shipping': 'Fournisseurs d\'expédition',
    'wizard.step4.integrations.accounting': 'Logiciels de comptabilité',
    'wizard.step4.integrations.support': 'Outils de support client',
    'wizard.step4.integrations.marketing': 'Automatisation marketing',
    'wizard.step4.integrations.api': 'Intégrations API',
    'wizard.step4.integrations.other': 'Autre',
    'wizard.step4.custom.functionality': 'Fonctionnalités Personnalisées',
    'wizard.step4.custom.functionality.placeholder': 'Décrivez toute fonctionnalité personnalisée ou caractéristique unique dont vous avez besoin qui n\'était pas listée ci-dessus...',
    'wizard.step4.mobile.requirements': 'Exigences Mobiles',
    'wizard.step4.mobile.requirements.placeholder': 'Sélectionnez l\'approche mobile',
    'wizard.step4.mobile.responsive': 'Design web adaptatif (fonctionne sur tous les appareils)',
    'wizard.step4.mobile.first': 'Approche design mobile-first',
    'wizard.step4.mobile.pwa': 'Application Web Progressive (PWA)',
    'wizard.step4.mobile.native': 'Application mobile native (iOS/Android)',
    'wizard.step4.mobile.hybrid': 'Application mobile hybride',
    'wizard.step4.mobile.desktop': 'Desktop seulement (pas d\'optimisation mobile)',
    'wizard.step4.error.core.features': 'Veuillez sélectionner au moins une fonctionnalité',
    'wizard.step4.error.mobile.requirements': 'Les exigences mobiles sont requises',

    // Project Wizard - Step 5
    'wizard.step5.title': 'Design & Image de Marque',
    'wizard.step5.design.style': 'Préférence de Style de Design',
    'wizard.step5.design.style.placeholder': 'Sélectionnez le style de design',
    'wizard.step5.design.style.modern': 'Moderne & Minimaliste',
    'wizard.step5.design.style.corporate': 'Corporate & Professionnel',
    'wizard.step5.design.style.creative': 'Créatif & Artistique',
    'wizard.step5.design.style.bold': 'Audacieux & Vibrant',
    'wizard.step5.design.style.elegant': 'Élégant & Sophistiqué',
    'wizard.step5.design.style.playful': 'Ludique & Amusant',
    'wizard.step5.design.style.industrial': 'Industriel & Tech',
    'wizard.step5.design.style.vintage': 'Vintage & Rétro',
    'wizard.step5.design.style.clean': 'Propre & Simple',
    'wizard.step5.design.style.custom': 'Personnalisé (sera décrit)',
    'wizard.step5.color.preferences': 'Préférences de Couleur',
    'wizard.step5.color.preferences.placeholder': 'Décrivez vos préférences de couleur. Avez-vous des couleurs de marque ? Des couleurs à éviter ? Palettes préférées ?',
    'wizard.step5.brand.guidelines': 'Directives de Marque Existantes',
    'wizard.step5.brand.guidelines.placeholder': 'Avez-vous des directives de marque, guides de style ou actifs de marque existants que nous devrions suivre ?',
    'wizard.step5.inspiration.sites': 'Sites Web d\'Inspiration',
    'wizard.step5.inspiration.sites.placeholder': 'Partagez les URLs de sites web que vous aimez et expliquez ce que vous appréciez (design, fonctionnalité, mise en page, etc.)',
    'wizard.step5.logo.requirements': 'Exigences Logo',
    'wizard.step5.logo.requirements.placeholder': 'Sélectionnez les besoins de logo',
    'wizard.step5.logo.have': 'Nous avons un logo existant',
    'wizard.step5.logo.need': 'Nous avons besoin d\'un nouveau logo',
    'wizard.step5.logo.update': 'Nous voulons mettre à jour notre logo existant',
    'wizard.step5.logo.none': 'Pas de logo nécessaire',
    'wizard.step5.image.requirements': 'Exigences Images & Médias',
    'wizard.step5.image.requirements.placeholder': 'Sélectionnez l\'approche d\'images',
    'wizard.step5.image.client': 'Nous fournirons toutes les images/médias',
    'wizard.step5.image.stock': 'Utiliser des photos/médias de stock',
    'wizard.step5.image.professional': 'Besoin de photographie professionnelle',
    'wizard.step5.image.mixed': 'Approche mixte (certaines fournies, d\'autres sourcées)',
    'wizard.step5.image.custom': 'Besoin de graphiques/illustrations personnalisés',
    'wizard.step5.image.minimal': 'Exigences d\'images minimales',
    'wizard.step5.error.design.style': 'Le style de design est requis',
    'wizard.step5.error.color.preferences': 'Les préférences de couleur sont requises',
    'wizard.step5.error.image.requirements': 'Les exigences d\'images sont requises',

    // Project Wizard - Step 6 (Hosting)
    'wizard.step6.title': 'Hébergement & Infrastructure',
    'wizard.step6.hosting.preference': 'Préférence d\'Hébergement',
    'wizard.step6.hosting.preference.placeholder': 'Sélectionnez la préférence d\'hébergement',
    'wizard.step6.hosting.managed': 'Hébergement entièrement géré (nous nous occupons de tout)',
    'wizard.step6.hosting.shared': 'Hébergement partagé (économique)',
    'wizard.step6.hosting.vps': 'Hébergement VPS (plus de contrôle et de ressources)',
    'wizard.step6.hosting.dedicated': 'Serveur dédié (performance maximale)',
    'wizard.step6.hosting.cloud': 'Hébergement cloud (AWS, Google Cloud, etc.)',
    'wizard.step6.hosting.existing': 'Utiliser l\'hébergement existant',
    'wizard.step6.hosting.recommendations': 'Besoin de recommandations',
    'wizard.step6.domain.requirements': 'Exigences de Domaine',
    'wizard.step6.domain.requirements.placeholder': 'Sélectionnez les besoins de domaine',
    'wizard.step6.domain.have': 'Nous avons déjà un domaine',
    'wizard.step6.domain.need': 'Nous avons besoin d\'un nouveau domaine',
    'wizard.step6.domain.transfer': 'Nous devons transférer notre domaine',
    'wizard.step6.domain.subdomain': 'Nous utiliserons un sous-domaine',
    'wizard.step6.domain.multiple': 'Nous avons besoin de plusieurs domaines',
    'wizard.step6.domain.help': 'Besoin d\'aide pour choisir un domaine',
    'wizard.step6.performance.requirements': 'Exigences de Performance',
    'wizard.step6.performance.requirements.placeholder': 'Sélectionnez les besoins de performance',
    'wizard.step6.performance.basic': 'Performance de base (petit site web, faible trafic)',
    'wizard.step6.performance.standard': 'Performance standard (trafic moyen)',
    'wizard.step6.performance.high': 'Haute performance (fort trafic, chargement rapide)',
    'wizard.step6.performance.enterprise': 'Niveau entreprise (performance maximale)',
    'wizard.step6.performance.global': 'Performance globale (CDN, plusieurs régions)',
    'wizard.step6.performance.unsure': 'Pas sûr, besoin de recommandations',
    'wizard.step6.security.requirements': 'Exigences de Sécurité (Sélectionnez tout ce qui s\'applique)',
    'wizard.step6.security.ssl': 'Certificat SSL',
    'wizard.step6.security.updates': 'Mises à jour de sécurité régulières',
    'wizard.step6.security.malware': 'Analyse de logiciels malveillants',
    'wizard.step6.security.firewall': 'Protection par pare-feu',
    'wizard.step6.security.ddos': 'Protection DDoS',
    'wizard.step6.security.2fa': 'Authentification à deux facteurs',
    'wizard.step6.security.audits': 'Audits de sécurité réguliers',
    'wizard.step6.security.gdpr': 'Conformité RGPD',
    'wizard.step6.security.pci': 'Conformité PCI',
    'wizard.step6.security.custom': 'Mesures de sécurité personnalisées',
    'wizard.step6.backup.requirements': 'Exigences de Sauvegarde',
    'wizard.step6.backup.requirements.placeholder': 'Sélectionnez les besoins de sauvegarde',
    'wizard.step6.backup.daily': 'Sauvegardes automatisées quotidiennes',
    'wizard.step6.backup.weekly': 'Sauvegardes automatisées hebdomadaires',
    'wizard.step6.backup.monthly': 'Sauvegardes automatisées mensuelles',
    'wizard.step6.backup.realtime': 'Sauvegardes en temps réel',
    'wizard.step6.backup.manual': 'Sauvegardes manuelles uniquement',
    'wizard.step6.backup.none': 'Aucune exigence de sauvegarde',
    'wizard.step6.support.needs': 'Besoins de Support Technique',
    'wizard.step6.support.needs.placeholder': 'Sélectionnez le niveau de support',
    'wizard.step6.support.basic': 'Support de base (email, heures d\'ouverture)',
    'wizard.step6.support.standard': 'Support standard (email/téléphone, heures étendues)',
    'wizard.step6.support.priority': 'Support prioritaire (24/7, réponse plus rapide)',
    'wizard.step6.support.managed': 'Entièrement géré (nous gérons tous les problèmes techniques)',
    'wizard.step6.support.self': 'Auto-géré (support minimal nécessaire)',
    'wizard.step6.support.custom': 'Arrangement de support personnalisé',
    'wizard.step6.error.hosting.preference': 'La préférence d\'hébergement est requise',
    'wizard.step6.error.domain.requirements': 'Les exigences de domaine sont requises',
    'wizard.step6.error.performance.requirements': 'Les exigences de performance sont requises',
    'wizard.step6.error.backup.requirements': 'Les exigences de sauvegarde sont requises',
    'wizard.step6.error.support.needs': 'Les besoins de support technique sont requis',

    // Project Wizard - Step 7 (Evolution)
    'wizard.step7.title': 'Évolution Future & Maintenance',
    'wizard.step7.future.features': 'Fonctionnalités Futures (Sélectionnez les fonctionnalités que vous pourriez vouloir ajouter plus tard)',
    'wizard.step7.features.analytics': 'Analyses et rapports avancés',
    'wizard.step7.features.ai': 'Fonctionnalités alimentées par l\'IA',
    'wizard.step7.features.mobile': 'Développement d\'application mobile',
    'wizard.step7.features.ecommerce': 'Fonctionnalités e-commerce avancées',
    'wizard.step7.features.multilang': 'Expansion multilingue',
    'wizard.step7.features.api': 'Intégrations API',
    'wizard.step7.features.users': 'Gestion avancée des utilisateurs',
    'wizard.step7.features.automation': 'Flux de travail d\'automatisation',
    'wizard.step7.features.seo': 'Fonctionnalités SEO avancées',
    'wizard.step7.features.social': 'Intégration des médias sociaux',
    'wizard.step7.features.security': 'Fonctionnalités de sécurité avancées',
    'wizard.step7.features.performance': 'Optimisation des performances',
    'wizard.step7.features.integrations': 'Intégrations personnalisées',
    'wizard.step7.features.cms': 'Gestion de contenu avancée',
    'wizard.step7.features.marketing': 'Automatisation marketing',
    'wizard.step7.scalability.needs': 'Exigences d\'Évolutivité',
    'wizard.step7.scalability.needs.placeholder': 'Sélectionnez les besoins d\'évolutivité',
    'wizard.step7.scalability.minimal': 'Croissance minimale attendue',
    'wizard.step7.scalability.moderate': 'Croissance modérée attendue',
    'wizard.step7.scalability.high': 'Forte croissance attendue',
    'wizard.step7.scalability.enterprise': 'Évolutivité de niveau entreprise nécessaire',
    'wizard.step7.scalability.global': 'Expansion mondiale prévue',
    'wizard.step7.scalability.unsure': 'Incertain sur la croissance future',
    'wizard.step7.maintenance.preference': 'Préférence de Maintenance',
    'wizard.step7.maintenance.preference.placeholder': 'Sélectionnez l\'approche de maintenance',
    'wizard.step7.maintenance.full': 'Maintenance complète (nous nous occupons de tout)',
    'wizard.step7.maintenance.partial': 'Maintenance partielle (nous gérons le technique, vous le contenu)',
    'wizard.step7.maintenance.training': 'Basée sur la formation (nous formons votre équipe)',
    'wizard.step7.maintenance.self': 'Auto-gérée (support continu minimal)',
    'wizard.step7.maintenance.asneeded': 'Support au besoin (paiement par demande)',
    'wizard.step7.maintenance.custom': 'Plan de maintenance personnalisé',
    'wizard.step7.update.frequency': 'Fréquence de Mise à Jour Attendue',
    'wizard.step7.update.frequency.placeholder': 'Sélectionnez la fréquence de mise à jour',
    'wizard.step7.update.daily': 'Mises à jour quotidiennes',
    'wizard.step7.update.weekly': 'Mises à jour hebdomadaires',
    'wizard.step7.update.monthly': 'Mises à jour mensuelles',
    'wizard.step7.update.quarterly': 'Mises à jour trimestrielles',
    'wizard.step7.update.rarely': 'Rarement (contenu statique)',
    'wizard.step7.update.seasonal': 'Mises à jour saisonnières',
    'wizard.step7.update.asneeded': 'Au besoin',
    'wizard.step7.training.needs': 'Exigences de Formation',
    'wizard.step7.training.needs.placeholder': 'Sélectionnez les besoins de formation',
    'wizard.step7.training.none': 'Aucune formation nécessaire',
    'wizard.step7.training.basic': 'Formation de base (mises à jour de contenu)',
    'wizard.step7.training.comprehensive': 'Formation complète (toutes les fonctionnalités)',
    'wizard.step7.training.ongoing': 'Formation continue et support',
    'wizard.step7.training.documentation': 'Documentation uniquement',
    'wizard.step7.training.video': 'Tutoriels vidéo',
    'wizard.step7.training.live': 'Sessions de formation en direct',
    'wizard.step7.longterm.vision': 'Vision à Long Terme',
    'wizard.step7.longterm.vision.placeholder': 'Décrivez votre vision à long terme pour ce projet. Où le voyez-vous dans 2-3 ans ? Quels sont vos plans de croissance ?',
    'wizard.step7.error.scalability.needs': 'Les besoins d\'évolutivité sont requis',
    'wizard.step7.error.maintenance.preference': 'La préférence de maintenance est requise',
    'wizard.step7.error.update.frequency': 'La fréquence de mise à jour est requise',

    // Project Wizard - Step 8 (Budget)
    'wizard.step8.title': 'Budget & Calendrier',
    'wizard.step8.budget.range': 'Fourchette de Budget',
    'wizard.step8.budget.range.placeholder': 'Sélectionnez la fourchette de budget',
    'wizard.step8.budget.under5k': 'Moins de 5 000 $',
    'wizard.step8.budget.5k10k': '5 000 $ - 10 000 $',
    'wizard.step8.budget.10k25k': '10 000 $ - 25 000 $',
    'wizard.step8.budget.25k50k': '25 000 $ - 50 000 $',
    'wizard.step8.budget.50k100k': '50 000 $ - 100 000 $',
    'wizard.step8.budget.over100k': 'Plus de 100 000 $',
    'wizard.step8.budget.discuss': 'Préfère en discuter',
    'wizard.step8.budget.flexibility': 'Flexibilité du Budget',
    'wizard.step8.budget.flexibility.placeholder': 'Sélectionnez le niveau de flexibilité',
    'wizard.step8.flexibility.fixed': 'Budget fixe (ne peut être dépassé)',
    'wizard.step8.flexibility.some': 'Certaine flexibilité (jusqu\'à 10-20% de plus)',
    'wizard.step8.flexibility.flexible': 'Flexible (prêt à investir plus pour la qualité)',
    'wizard.step8.flexibility.value': 'Axé sur la valeur (meilleur ROI dans la raison)',
    'wizard.step8.flexibility.phased': 'Ouvert à une approche par phases',
    'wizard.step8.payment.preference': 'Préférence de Paiement',
    'wizard.step8.payment.preference.placeholder': 'Sélectionnez la structure de paiement',
    'wizard.step8.payment.milestone': 'Paiements basés sur les jalons',
    'wizard.step8.payment.monthly': 'Paiements mensuels',
    'wizard.step8.payment.5050': '50% d\'acompte, 50% à la livraison',
    'wizard.step8.payment.thirds': 'Trois paiements égaux',
    'wizard.step8.payment.completion': 'Paiement complet à la livraison',
    'wizard.step8.payment.custom': 'Plan de paiement personnalisé',
    'wizard.step8.timeline': 'Calendrier Souhaité',
    'wizard.step8.timeline.placeholder': 'Sélectionnez le calendrier',
    'wizard.step8.timeline.asap': 'ASAP (projet urgent)',
    'wizard.step8.timeline.1month': 'Dans le mois',
    'wizard.step8.timeline.2to3months': '2-3 mois',
    'wizard.step8.timeline.3to6months': '3-6 mois',
    'wizard.step8.timeline.6to12months': '6-12 mois',
    'wizard.step8.timeline.overyear': 'Plus d\'un an',
    'wizard.step8.timeline.flexible': 'Calendrier flexible',
    'wizard.step8.priority.features': 'Fonctionnalités Prioritaires (si budget limité)',
    'wizard.step8.priority.features.placeholder': 'Si nous devons travailler avec un budget plus serré, quelles fonctionnalités sont les plus importantes pour vous ? Que peut-on ajouter plus tard ?',
    'wizard.step8.budget.concerns': 'Préoccupations ou Questions sur le Budget',
    'wizard.step8.budget.concerns.placeholder': 'Avez-vous des préoccupations concernant le budget ? Des questions sur les tarifs ? Autre chose que nous devrions savoir ?',
    'wizard.step8.error.budget.range': 'La fourchette de budget est requise',
    'wizard.step8.error.budget.flexibility': 'La flexibilité du budget est requise',
    'wizard.step8.error.payment.preference': 'La préférence de paiement est requise',
    'wizard.step8.error.timeline': 'Le calendrier est requis',
    'wizard.step8.error.priority.features': 'Les fonctionnalités prioritaires sont requises',

    // Project Wizard - Step 9 (Other)
    'wizard.step9.title': 'Détails Finaux',
    'wizard.step9.additional.requirements': 'Exigences Supplémentaires',
    'wizard.step9.additional.requirements.placeholder': 'Des exigences, fonctionnalités ou spécifications supplémentaires qui n\'ont pas été couvertes dans les étapes précédentes ?',
    'wizard.step9.concerns': 'Préoccupations ou Défis',
    'wizard.step9.concerns.placeholder': 'Avez-vous des préoccupations concernant le projet ? Des expériences passées avec le développement web ? Des défis spécifiques qui vous inquiètent ?',
    'wizard.step9.questions': 'Questions pour Nous',
    'wizard.step9.questions.placeholder': 'Quelles questions avez-vous pour nous ? À propos de notre processus, calendrier, tarifs, ou autre chose ?',
    'wizard.step9.communication.preference': 'Préférence de Communication',
    'wizard.step9.communication.preference.placeholder': 'Sélectionnez la préférence de communication',
    'wizard.step9.communication.email': 'Email',
    'wizard.step9.communication.phone': 'Appels téléphoniques',
    'wizard.step9.communication.video': 'Appels vidéo',
    'wizard.step9.communication.slack': 'Slack/Teams',
    'wizard.step9.communication.project': 'Outil de gestion de projet',
    'wizard.step9.communication.mixed': 'Approche mixte',
    'wizard.step9.decision.makers': 'Décideurs',
    'wizard.step9.decision.makers.placeholder': 'Qui sera impliqué dans la prise de décisions sur ce projet ? Devrions-nous inclure quelqu\'un d\'autre dans les communications ?',
    'wizard.step9.additional.info': 'Autre Chose ?',
    'wizard.step9.additional.info.placeholder': 'Y a-t-il autre chose que vous aimeriez que nous sachions sur votre projet, votre entreprise, ou vos attentes ?',
    'wizard.step9.ready.title': 'Prêt à Soumettre Votre Brief de Projet ?',
    'wizard.step9.ready.description': 'Une fois que vous soumettrez ce brief de projet, notre équipe examinera vos exigences et vous répondra dans les 24-48 heures avec :',
    'wizard.step9.ready.proposal': 'Une proposition de projet détaillée',
    'wizard.step9.ready.pricing': 'Calendrier et tarifs précis',
    'wizard.step9.ready.nextsteps': 'Prochaines étapes pour avancer',
    'wizard.step9.ready.answers': 'Réponses à toutes vos questions',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.name.required': 'Le nom est requis',
    'common.email.required': 'L\'email est requis',
    'common.email.invalid': 'Veuillez entrer une adresse email valide',
    'common.message.required': 'Le message est requis',
    'common.password.required': 'Le mot de passe est requis',
    'common.service.required': 'Veuillez sélectionner un type de service',
    'common.required': 'Requis',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};